# UNOCHA DATA Exploration

1. Need to import two data sets: "project summary" contains all projects within each CBPF and "contribution" includes countries and contributions. 
2. Understanding the various columns to have proper filters.

In [36]:
import pandas as pd

PROJECT_SUMMARY_URL = "https://cbpfapi.unocha.org/vo1/odata/ProjectSummary?$format=csv"
CONTRIBUTION_URL = "https://cbpfapi.unocha.org/vo1/odata/Contribution?$format=csv&includeTransfer=1"

projects = pd.read_csv(PROJECT_SUMMARY_URL, low_memory=False)
contrib = pd.read_csv(CONTRIBUTION_URL, low_memory=False)

projects.shape, contrib.shape

((16890, 52), (4476, 23))

In [37]:
contrib.columns.tolist()

['PooledFundId',
 'PooledFundName',
 'PooledFundCodeAbbrv',
 'ContributionCode',
 'FiscalYear',
 'DonorName',
 'DonorCode',
 'GMSDonorID',
 'GMSDonorName',
 'CountryCode',
 'PledgeDate',
 'PledgeAmt',
 'PipeLineDate',
 'PaidDate',
 'PaidAmt',
 'ExpectedDate',
 'PledgeAmtLocalCurrency',
 'PledgeAmtCurrencyExchangeRate',
 'PaidAmtLocalCurrency',
 'PaidAmtCurrencyExchangeRate',
 'PledgeAmtLocal',
 'PaidAmtLocal',
 'IsTransfer']

# We now have the variables to filter by. 

1. 'DonorName' 
2. 'FiscalYear'

In [38]:
usg_2026 = contrib[
    (contrib["DonorName"] == "United States") &
    (contrib["FiscalYear"] == 2026)
]

usg_2026

,PooledFundId,PooledFundName,PooledFundCodeAbbrv,ContributionCode,FiscalYear,DonorName,DonorCode,GMSDonorID,GMSDonorName,CountryCode,...,PaidDate,PaidAmt,ExpectedDate,PledgeAmtLocalCurrency,PledgeAmtCurrencyExchangeRate,PaidAmtLocalCurrency,PaidAmtCurrencyExchangeRate,PledgeAmtLocal,PaidAmtLocal,IsTransfer
259,99,Bangladesh (AP-RHPF),AP501,ERF/B_RHPF_AP-US/78003/85333/2026,2026,United States,102,102.0,United States,US,...,3/13/2026 12:00:00 AM,150000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,150000000.0,150000000.0,0
548,90,Chad (RhPF-WCA),TCD90,ERF/TD_RHPF-US/77989/85309/2026,2026,United States,102,102.0,United States,US,...,3/13/2026 12:00:00 AM,100000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,100000000.0,100000000.0,0
592,87,Colombia (RhPF-LAC),COL87,ERF/C_RHPF_LAC-US/77989/85382/2026,2026,United States,102,102.0,United States,US,...,3/13/2026 12:00:00 AM,100000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,100000000.0,100000000.0,0
827,24,DRC,DRC24,ERF/DRC_HF-US/77991/85311/2026,2026,United States,102,102.0,United States,US,...,3/10/2026 12:00:00 AM,150000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,150000000.0,150000000.0,0
830,24,DRC,DRC24,ERF/DRC_HF-US/78156/85678/2026,2026,United States,102,102.0,United States,US,...,1/1/0001 12:00:00 AM,0.0,1/1/0001 12:00:00 AM,USD,1.0,USD,0.0,225000000.0,0.0,0
836,509,El Salvador (RhPF-LAC),SV509,ERF/EL_RHPF_LAC-US/77989/85384/2026,2026,United States,102,102.0,United States,US,...,3/13/2026 12:00:00 AM,25000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,25000000.0,25000000.0,0
1163,53,Ethiopia,ETH53,ERF/3379-US/77991/85337/2026,2026,United States,102,102.0,United States,US,...,3/10/2026 12:00:00 AM,100000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,100000000.0,100000000.0,0
1171,508,Guatemala (RhPF-LAC),GT508,ERF/GU_RHPF_LAC-US/77989/85385/2026,2026,United States,102,102.0,United States,US,...,3/13/2026 12:00:00 AM,60000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,60000000.0,60000000.0,0
1298,88,Haiti (RhPF-LAC),HTI88,ERF/H_RHPF_LAC-US/77991/85341/2026,2026,United States,102,102.0,United States,US,...,3/10/2026 12:00:00 AM,125000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,125000000.0,125000000.0,0
1300,510,Honduras (RhPF-LAC),HN510,ERF/HO_RHPF_LAC-US/77989/85386/2026,2026,United States,102,102.0,United States,US,...,3/13/2026 12:00:00 AM,65000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,65000000.0,65000000.0,0
1448,511,Kenya (ESAHF),KE511,ERF/K_RHPF_SEA-US/78003/85334/2026,2026,United States,102,102.0,United States,US,...,3/13/2026 12:00:00 AM,50000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,50000000.0,50000000.0,0
1671,89,Mozambique (RhPF),MOZ89,ERF/M_RHPF_SEA-US/77989/85383/2026,2026,United States,102,102.0,United States,US,...,3/13/2026 12:00:00 AM,80000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,80000000.0,80000000.0,0
1852,59,Myanmar,MMR59,ERF/3415-US/77989/85387/2026,2026,United States,102,102.0,United States,US,...,3/13/2026 12:00:00 AM,140000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,140000000.0,140000000.0,0
2066,75,Nigeria,NGA75,ERF/NIG_ERF-US/77991/85338/2026,2026,United States,102,102.0,United States,US,...,3/10/2026 12:00:00 AM,125000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,125000000.0,125000000.0,0
2991,19,South Sudan,SSD19,ERF/SSHF-US/77991/85339/2026,2026,United States,102,102.0,United States,US,...,3/10/2026 12:00:00 AM,100000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,100000000.0,100000000.0,0
2994,19,South Sudan,SSD19,ERF/SSHF-US/78156/85679/2026,2026,United States,102,102.0,United States,US,...,1/1/0001 12:00:00 AM,0.0,1/1/0001 12:00:00 AM,USD,1.0,USD,0.0,50000000.0,0.0,0
3295,15,Sudan,SUD15,ERF/SUHF-US/77985/85241/2026,2026,United States,102,102.0,United States,US,...,3/4/2026 12:00:00 AM,200000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,200000000.0,200000000.0,0
3560,62,Syria,SYR62,ERF/3558-US/77991/85340/2026,2026,United States,102,102.0,United States,US,...,3/10/2026 12:00:00 AM,150000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,150000000.0,150000000.0,0
3837,512,Uganda (ESAHF),UG512,ERF/UGA_RHPF_SEA-US/78003/85323/2026,2026,United States,102,102.0,United States,US,...,3/13/2026 12:00:00 AM,75000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,75000000.0,75000000.0,0
3838,512,Uganda (ESAHF),UG512,ERF/UGA_RHPF_SEA-US/78156/85680/2026,2026,United States,102,102.0,United States,US,...,1/1/0001 12:00:00 AM,0.0,1/1/0001 12:00:00 AM,USD,1.0,USD,0.0,75000000.0,0.0,0
4049,81,Ukraine,UKR81,ERF/UKR_CBPF-US/77989/85388/2026,2026,United States,102,102.0,United States,US,...,3/13/2026 12:00:00 AM,155000000.0,1/1/0001 12:00:00 AM,USD,1.0,USD,1.0,155000000.0,155000000.0,0

In [39]:
usg_2026[
    [
        "PooledFundName",
        "PledgeAmt",
        "PaidAmt",
        "PledgeDate",
        "PaidDate",
    ]
]

,PooledFundName,PledgeAmt,PaidAmt,PledgeDate,PaidDate
259,Bangladesh (AP-RHPF),150000000.0,150000000.0,2/19/2026 12:00:00 AM,3/13/2026 12:00:00 AM
548,Chad (RhPF-WCA),100000000.0,100000000.0,2/25/2026 12:00:00 AM,3/13/2026 12:00:00 AM
592,Colombia (RhPF-LAC),100000000.0,100000000.0,2/25/2026 12:00:00 AM,3/13/2026 12:00:00 AM
827,DRC,150000000.0,150000000.0,2/20/2026 12:00:00 AM,3/10/2026 12:00:00 AM
830,DRC,225000000.0,0.0,6/2/2026 12:00:00 AM,1/1/0001 12:00:00 AM
836,El Salvador (RhPF-LAC),25000000.0,25000000.0,2/25/2026 12:00:00 AM,3/13/2026 12:00:00 AM
1163,Ethiopia,100000000.0,100000000.0,2/20/2026 12:00:00 AM,3/10/2026 12:00:00 AM
1171,Guatemala (RhPF-LAC),60000000.0,60000000.0,2/25/2026 12:00:00 AM,3/13/2026 12:00:00 AM
1298,Haiti (RhPF-LAC),125000000.0,125000000.0,2/20/2026 12:00:00 AM,3/10/2026 12:00:00 AM
1300,Honduras (RhPF-LAC),65000000.0,65000000.0,2/25/2026 12:00:00 AM,3/13/2026 12:00:00 AM
1448,Kenya (ESAHF),50000000.0,50000000.0,2/19/2026 12:00:00 AM,3/13/2026 12:00:00 AM
1671,Mozambique (RhPF),80000000.0,80000000.0,2/25/2026 12:00:00 AM,3/13/2026 12:00:00 AM
1852,Myanmar,140000000.0,140000000.0,2/25/2026 12:00:00 AM,3/13/2026 12:00:00 AM
2066,Nigeria,125000000.0,125000000.0,2/20/2026 12:00:00 AM,3/10/2026 12:00:00 AM
2991,South Sudan,100000000.0,100000000.0,2/20/2026 12:00:00 AM,3/10/2026 12:00:00 AM
2994,South Sudan,50000000.0,0.0,6/2/2026 12:00:00 AM,1/1/0001 12:00:00 AM
3295,Sudan,200000000.0,200000000.0,2/6/2026 12:00:00 AM,3/4/2026 12:00:00 AM
3560,Syria,150000000.0,150000000.0,2/20/2026 12:00:00 AM,3/10/2026 12:00:00 AM
3837,Uganda (ESAHF),75000000.0,75000000.0,2/19/2026 12:00:00 AM,3/13/2026 12:00:00 AM
3838,Uganda (ESAHF),75000000.0,0.0,6/2/2026 12:00:00 AM,1/1/0001 12:00:00 AM
4049,Ukraine,155000000.0,155000000.0,2/25/2026 12:00:00 AM,3/13/2026 12:00:00 AM

# We now know how much $ the US contributes to each pooled fund for FY26. 

# I'd like to now create custom data frames for each of the USG traches: 1. for the 2025 MOU and 2026 second tranche.

In [40]:
# -------------------------------------
# Official announcement reference tables
# -------------------------------------

mou_2025 = pd.DataFrame({
    "Country": [
        "Guatemala",
        "Honduras",
        "El Salvador",
        "Ukraine",
        "Haiti",
        "Nigeria",
        "Ethiopia",
        "South Sudan",
        "Mozambique",
        "Myanmar",
        "DRC",
        "Sudan",
        "Bangladesh",
        "Syria",
        "Uganda",
        "Kenya",
        "Chad",
    ],
    "Announcement": "Initial MOU",
    "AnnouncementDate": "2025-12-29",
})

tranche2 = pd.DataFrame({
    "Country": [
        "Bangladesh",
        "Myanmar",
        "Central African Republic",
        "Chad",
        "Colombia",
        "DRC",
        "El Salvador",
        "Ethiopia",
        "Guatemala",
        "Haiti",
        "Honduras",
        "Kenya",
        "Lebanon",
        "Mozambique",
        "Nigeria",
        "South Sudan",
        "Sudan",
        "Syria",
        "Uganda",
        "Ukraine",
        "Venezuela",
    ],
    "Announcement": "Tranche 2",
    "AnnouncementDate": "2026-05-14",
})